language: nix
sudo: required
os:
- linux
jobs:
  include:
    - stage: test
      name: emacs25
      env: COMMAND=testEmacs25
    - name: emacs26
      env: COMMAND=testEmacs26
env:
  global:
    - NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz
install:
- nix-shell nix/shell.nix --run 'exit 0'
script:
- nix-shell nix/shell.nix --run "${COMMAND}"
